### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by millerh1** [naomihabiblab/5xFAD-sNucSeq#1]
The paper said the code was available here. https://www.nature.com/articles/s41593-020-0624-8#data-availability

Could you please push the code?

**Comment by naomihabiblab** [comment]
Yes. Thank you for letting me know that it’s missing.

**Comment by millerh1** [comment]
Thank you!

**Comment by rebeccawuu** [comment]
I was wondering if the code would be put back up any time soon?

**Comment by millerh1** [comment]
It's been a month. Where is the code?

**Comment by fentouxungui** [comment]
where is the code?

**Comment by samuel-marsh** [comment]
Hi,

I'm also wondering if you could please push the code?  

Thanks!
